package com.example.growCare.data.repository

import android.net.Uri
import com.example.growCare.data.local.datasource.DiseaseAnalysisLocalDataSource
import com.example.growCare.data.local.inference.LocalChatInference
import com.example.growCare.data.local.inference.LocalDiseaseInference
import com.example.growCare.data.mapper.DiseaseAnalysisMapper
import com.example.growCare.domain.model.DiseaseAnalysis
import com.example.growCare.domain.model.DiseaseSeverity
import com.example.growCare.domain.repository.DetectionRepository
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.flow
import java.util.UUID
import javax.inject.Inject
import javax.inject.Singleton

/**
 * Implementation of DetectionRepository
 * Handles disease detection and dynamic AI advice generation using Gemma.
 */
@Singleton
class DetectionRepositoryImpl @Inject constructor(
    private val localDiseaseInference: LocalDiseaseInference,
    private val diseaseAnalysisLocalDataSource: DiseaseAnalysisLocalDataSource,
    private val diseaseAnalysisMapper: DiseaseAnalysisMapper,
    private val localChatInference: LocalChatInference
) : DetectionRepository {

    private fun getCurrentUserId(): String {
        return "local-user"
    }

    override suspend fun analyzePlantDisease(
        imageUri: Uri,
        cropName: String?,
    ): Result<DiseaseAnalysis> {
        return try {
            val userId = getCurrentUserId()
            
            // 1. Get YOLO prediction
            val result = localDiseaseInference.detectDisease(imageUri, cropName)
            
            val isHealthy = result.diseaseName.contains("Healthy", ignoreCase = true) || 
                            result.diseaseName.contains("Unable to Classify", ignoreCase = true)
            
            val finalSymptoms: List<String>
            val finalTreatment: List<String>
            val finalPrevention: List<String>
            val finalNotes: String
            
            if (isHealthy) {
                // 2a. Use static defaults for healthy / unable to classify states
                finalSymptoms = result.symptoms
                finalTreatment = result.treatment
                finalPrevention = result.prevention
                finalNotes = result.additionalNotes ?: ""
            } else {
                // 2b. Generate dynamic advice for detected diseases using Gemma
                val generatedAdvice = localChatInference.generateDiseaseAdvice(result.diseaseName)
                
                // Parse the structured text if generation succeeded, else fallback
                if (generatedAdvice.isNotBlank()) {
                    finalSymptoms = parseGemmaAdvice(generatedAdvice, "Symptoms")
                    finalTreatment = parseGemmaAdvice(generatedAdvice, "Treatment")
                    finalPrevention = parseGemmaAdvice(generatedAdvice, "Prevention")
                    finalNotes = (result.additionalNotes ?: "") + " • Advice generated by Gemma AI."
                } else {
                    finalSymptoms = listOf("Inspect leaves, stems, and roots for visible damage.")
                    finalTreatment = listOf("Consult a local agricultural extension officer.")
                    finalPrevention = listOf("Maintain good crop hygiene and monitor regularly.")
                    finalNotes = (result.additionalNotes ?: "") + " • Gemma AI advice generation failed."
                }
            }

            val diseaseAnalysis = DiseaseAnalysis(
                id = UUID.randomUUID().toString(),
                userId = userId,
                cropName = cropName,
                imageUrl = imageUri.toString(),
                diseaseName = result.diseaseName,
                confidence = result.confidence,
                symptoms = finalSymptoms,
                severity = when {
                    result.confidence >= 80 && !isHealthy -> DiseaseSeverity.SEVERE
                    result.confidence >= 50 && !isHealthy -> DiseaseSeverity.MODERATE
                    else -> DiseaseSeverity.MILD
                },
                treatment = finalTreatment,
                prevention = finalPrevention,
                additionalNotes = finalNotes,
                timestamp = System.currentTimeMillis(),
            )

            saveDiseaseAnalysis(diseaseAnalysis)
            
            Result.success(diseaseAnalysis)
        } catch (e: Exception) {
            Result.failure(e)
        }
    }

    private fun parseGemmaAdvice(output: String, section: String): List<String> {
        val lines = output.lines()
        val result = mutableListOf<String>()
        var inSection = false
        for (line in lines) {
            val trimmed = line.trim()
            if (trimmed.equals("$section:", ignoreCase = true) || 
                trimmed.equals(section, ignoreCase = true) || 
                trimmed.equals("**$section:**", ignoreCase = true)) {
                inSection = true
                continue
            }
            if (inSection) {
                // If we hit another header (no bullet points, ends with :), stop parsing
                if (trimmed.isNotEmpty() && !trimmed.startsWith("-") && !trimmed.startsWith("*") && !trimmed.matches(Regex("^\\d+\\..*"))) {
                    if (trimmed.endsWith(":") || trimmed.lowercase() == "treatment:" || trimmed.lowercase() == "prevention:") {
                        break
                    }
                }
                // Add list items
                if (trimmed.isNotEmpty() && (trimmed.startsWith("-") || trimmed.startsWith("*") || trimmed.matches(Regex("^\\d+\\..*")))) {
                    result.add(trimmed.replace(Regex("^[-*\\d.\\s]+"), "").trim())
                }
            }
        }
        return if (result.isEmpty()) listOf("No specific advice generated.") else result
    }

    override fun getDiseaseHistory(): Flow<List<DiseaseAnalysis>> = flow {
        try {
            val userId = getCurrentUserId()
            diseaseAnalysisLocalDataSource.getUserAnalyses(userId).collect { entities ->
                val analyses = diseaseAnalysisMapper.toDomainList(entities)
                emit(analyses)
            }
        } catch (_: Exception) {
            emit(emptyList())
        }
    }

    override suspend fun getDiseaseAnalysisById(analysisId: String): Result<DiseaseAnalysis?> {
        return try {
            val entity = diseaseAnalysisLocalDataSource.getAnalysisById(analysisId)
            Result.success(entity?.let { diseaseAnalysisMapper.toDomain(it) })
        } catch (e: Exception) {
            Result.failure(e)
        }
    }

    override suspend fun deleteDiseaseAnalysis(analysisId: String): Result<Unit> {
        return try {
            val existing = diseaseAnalysisLocalDataSource.getAnalysisById(analysisId)
            existing?.let { diseaseAnalysisLocalDataSource.deleteAnalysis(it) }
            Result.success(Unit)
        } catch (e: Exception) {
            Result.failure(e)
        }
    }

    override suspend fun saveDiseaseAnalysis(analysis: DiseaseAnalysis): Result<Unit> {
        return try {
            diseaseAnalysisLocalDataSource.saveAnalysis(
                diseaseAnalysisMapper.toEntity(analysis)
            )
            Result.success(Unit)
        } catch (e: Exception) {
            Result.failure(e)
        }
    }

    override fun getDiseasesBySeverity(severity: DiseaseSeverity): Flow<List<DiseaseAnalysis>> = flow {
        getDiseaseHistory().collect { analyses ->
            emit(analyses.filter { it.severity == severity })
        }
    }
}
